### ISSUE TITLE
trinket sim page table cuts off improperly

### ISSUE THREAD

**Issue by jmuravsky** [WarcraftPriests/WarcraftPriests.github.io#40]
the github.io page with the trinket sim table cuts off at around 180 ilvl for all trinkets for me, screencap included.
<img width="447" alt="not ok" src="https://user-images.githubusercontent.com/9059268/106872822-09e47880-66d4-11eb-8a8a-b18fdf795f70.PNG">

**Comment by lutzmor** [comment]
Thx yeah working on a fix something changed in highcharts and he is interpreting the values wrong :(.

**Comment by lutzmor** [comment]
Should be back to normal :)
